# The new prompt
format = """ $character$time$directory$git_branch$rust$python$conda$cmd_duration """
# right align is only configurable on zsh and fish
add_newline = false

# Break the new line at the start of the prompt
[line_break]
disabled = false


# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜ ](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[➜ ](bold red)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

# Truncate the path of the directory to only the basename
[directory]
style = " bold #7bdef1"
truncation_length = 2


# Show the time in the command prompt
[time]
disabled = false
time_format = "%R"
style = "#545c7e"
format = "[$time]($style) "

[cmd_duration]
min_time = 1000
style = "bold #545c7e"
#format = "[       - $duration]($style)"
format = "[ - $duration]($style)"
show_milliseconds = false

# Configures the python prompt
[python]
symbol = " "
format = '[ ${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

# Configures the rust prompt
[rust]
format = "[ ${symbol}(${version} )]($style)"
style = "#fa6e79"

# Configures the lua prompt
[lua]
format = "[ $symbol]($style)"
symbol = " lua"

# Configures the conda prompt
[conda]
truncation_length = 0
style = "bold #1B9858"
format = ' [$symbol$environment]($style) '

# Configures the github prompt
[git_branch]
symbol = " "
style = "#A779FF"
format = "[ $symbol$branch(:$remote_branch)]($style) "

[git_status]
disabled = true
